Consider the below code to answer further questions:

In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [2]:
print(type(list_))

<class 'list'>


In [3]:
print(type(array_list))

<class 'numpy.ndarray'>


yes, there is a difference in their data types. As you can see, list_ is of type list, which is a built-in Python data type for creating lists of items. array_list, on the other hand, is of type numpy.ndarray, which is a data type provided by the NumPy library for creating arrays of numerical data.

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [4]:
print(type(list_))

<class 'list'>


In [5]:
print(type(array_list))

<class 'numpy.ndarray'>


Q3. Considering the following changes in the variable, array_list:

In [6]:
array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.


In [7]:
print("Type of each element of variable list_")
for i in list_ :
    print(type(i))
print("Types of each element of variable array_list")
for j in array_list :
    print(type(j))

Type of each element of variable list_
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Types of each element of variable array_list
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Consider the below code to answer further questions:

In [8]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

find shape

In [9]:
np.shape(num_array)

(2, 3)

find size

In [11]:
np.size(num_array)

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [12]:
import numpy as np
array = np.zeros((3,3))
print(array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [13]:
import numpy as np
identity_array = np.eye(5)
print(identity_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
